[ 2025-07-03 17:08:51,299 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2025-07-03 17:08:51,300 ] root - INFO - Getting the data from mongodb
[ 2025-07-03 17:08:51,300 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2025-07-03 17:08:51,301 ] root - INFO - Exporting data from mongodb
[ 2025-07-03 17:08:51,302 ] root - ERROR - Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-07-03 17:08:51,302 ] root - ERROR - Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-07-03 17:08:51,303 ] root - ERROR - Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-07-03 17:08:51,304 ] root - ERROR - Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-07-03 17:08:51,304 ] root - ERROR - Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\pipline\training_pipeline.py] at line number [47]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-07-03 17:08:51,305 ] root - ERROR - Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\pipline\training_pipeline.py] at line number [133]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\pipline\training_pipeline.py] at line number [47]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\components\data_ingestion.py] at line number [86]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\components\data_ingestion.py] at line number [34]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\data_access\proj1_data.py] at line number [20]: Error occurred in python script: [C:\Users\91638\Desktop\MLOps\src\configuration\mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
